name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip
  - pip:
    - nbgitpuller 
    - pandas
    - matplotlib
    - vtk
    - mayavi
    - ipython
    - ipywidgets
    - ipyevents
    
